language: java

# Use container based builds. They are faster and we do not need sudo.
sudo: false

jdk:
  - openjdk11
  - oraclejdk11
  
dist: focal

script: 
 - mvn -P packaging-jar install verify

branches:
  only:
  - master
  